# Generated by Django 5.1.4 on 2024-12-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.CharField(default='Unknown Hotel', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
