# Generated by Django 5.1.4 on 2024-12-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_hotel_name_booking_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_price',
        ),
    ]
